### ISSUE TITLE
when nan/inf in reco variable, binning is -1 and things break downstream

### ISSUE THREAD

**Issue by markrosslonergan** [markrosslonergan/Elephant_Vanishes#38]

**Comment by markrosslonergan** [comment]
Just at the point of loading, don't load inf/nan and simply skip that. Helps avoid more checks.

**Comment by ibsafa** [comment]
Linked pull request fixes the problem. A check did exist to skip processing the event, but it was being done after the PROpeller is filled.  Could this have been causing other problems, because with this bug we basically had events that had no associated syststruct splines/systematics, or at the very least the indices were out of whack.
